#!/usr/bin/env bash

# This file is automatically generated by the Nebula SDK. DO NOT EDIT.

set -euo pipefail

#
# Commands
#

DOCKER="${DOCKER:-docker}"

#
#
#

{{ range .Images }}
$DOCKER build -t {{ .Ref }} -f {{ .Filename }} .
{{- end }}
