#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

BUILD_PROGRAMS=( ${BUILD_PROGRAMS:-$( relay::sdk::go::default_programs )} )

for PROGRAM in "${BUILD_PROGRAMS[@]}"; do
  echo "# build (go): ${PROGRAM}"
  scripts/build "${PROGRAM}"
done
