#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

GO_DIST_OS_ARCHES=( linux-amd64 linux-386 linux-arm64 linux-ppc64le linux-s390x windows-amd64 darwin-amd64 )
GO_DIST_PROGRAMS=( $( relay::sdk::go::default_programs ) )

for PROGRAM in "${GO_DIST_PROGRAMS[@]}"; do
  for OS_ARCH in "${GO_DIST_OS_ARCHES[@]}"; do
    echo "# dist: ${PROGRAM} ${OS_ARCH}"
    GOOS="${OS_ARCH%-*}" GOARCH="${OS_ARCH##*-}" scripts/dist "${PROGRAM}"
  done
done
