#!/usr/bin/env bash
set -euo pipefail

#
# Commands
#

GO="${GO:-go}"
GIT="${GIT:-git}"

#
#
#

set -x
$GO generate ./...

if [ -n "$( $GIT status --porcelain --untracked-files=no )" ]; then
    exit 1
fi
