#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

RELEASE_PROGRAMS=( $( relay::sdk::go::default_programs ) )

for PROGRAM in "${RELEASE_PROGRAMS[@]}"; do
  echo "# release: ${PROGRAM}"
  scripts/release "${PROGRAM}"
done
