#!/usr/bin/env bash
set -euo pipefail

#
# Variables
#

ARTIFACTS_BUCKET="${ARTIFACTS_BUCKET:-nebula-packages}"
ARTIFACTS_DIR="${ARTIFACTS_DIR:-artifacts}"

#
#
#

. scripts/library.sh

[[ "$#" -eq 1 ]] || relay::sdk::go::usage "$0 <program>"

eval "$( relay::sdk::go::cli_vars "$1" )"

PACKAGE_KEY_PREFIX="gs://${ARTIFACTS_BUCKET}/sdk/${CLI_NAME}"

for PACKAGE in $( relay::sdk::go::cli_artifacts "$1" "${ARTIFACTS_DIR}/${CLI_NAME}" ); do
  # Get the remaining file path and extension (directory, name and version
  # truncated) from the package.
  CLI_PLATFORM_EXT="-$( relay::sdk::go::cli_platform_ext "$1" "${PACKAGE}" )"
  relay::sdk::go::release "${ARTIFACTS_BUCKET}" "${CLI_NAME}" "${PACKAGE}" "${CLI_PLATFORM_EXT}"
  relay::sdk::go::release "${ARTIFACTS_BUCKET}" "${CLI_NAME}" "${PACKAGE}.sha256" "${CLI_PLATFORM_EXT}.sha256"
done
