#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

RELEASE_PROGRAMS=( $( nebula::sdk::default_programs ) )

for PROGRAM in "${RELEASE_PROGRAMS[@]}"; do
  echo "# release (go): ${PROGRAM}"
  scripts/release "${PROGRAM}"
done

echo "# release (python)"
(
  pushd support/python >/dev/null
  scripts/release
)
