#!/usr/bin/env bash
set -euo pipefail

#
# Commands
#

GO="${GO:-go}"

#
#
#

echo '# test (go)'
(
    set -x
    $GO test -v -race ./...
)

echo '# test (python)'
(
    pushd support/python >/dev/null
    scripts/test
)
